# WE CAN USE THIS FILE ALONG WITH REST CLIENT EXTENSION TO TEST ROUTES/API FETCH
# USE 3 "###" to start a new request

GET https://fakestoreapi.com/products

###

GET https://fakestoreapi.com/products/categories

###

GET http://localhost:3001/api/items

###

GET http://localhost:3001/api/users/:id
Content-Type: application/json

{
  "_id": "62cdcb57f1732c33c706c2ad"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Marco",
  "email": "marco@gmail.com",
  "password": "test"
}

###

GET http://localhost:3001/api/purchases/mycart/

###

DELETE http://localhost:3000/api/users/:id
Content-Type: application/json

{
  "userId": "62cd1f2a8ea0c2843ac9adc2"
}

###

PUT http://localhost:3000/api/users/update
Content-Type: application/json
# Authorized: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyY2M1NTc5YzhjMzE5ZDYzYzc4NThjYiIsIm5hbWUiOiJNZWdhbiIsImVtYWlsIjoibWVnYW5AZ21haWwuY29tIiwiY3JlYXRlZEF0IjoiMjAyMi0wNy0xMVQxNjo1MzoxMy4wMTZaIiwidXBkYXRlZEF0IjoiMjAyMi0wNy0xMVQxNjo1MzoxMy4wMTZaIiwiX192IjowfSwiaWF0IjoxNjU3NTU4NDA0LCJleHAiOjE2NTc2NDQ4MDR9.69hcx2DnabsGrxgh16shRjkPWKvPAEnFAKTutiAEMaU

{
  "_id": "62c87747c1c54d66cc680e08",
  "email": "jess@gmail.com"
}

