# WE CAN USE THIS FILE ALONG WITH REST CLIENT EXTENSION TO TEST ROUTES/API FETCH
# USE 3 "###" to start a new request

GET https://fakestoreapi.com/products

###

GET https://fakestoreapi.com/products/categories

###

GET http://localhost:3001/api/items

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Daniel",
  "email": "daniel@gmail.com",
  "password": "test"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Patrick",
  "email": "patrick@gmail.com",
  "password": "test"
}

###

GET http://localhost:3001/api/purchases/mycart/

###

DELETE http://localhost:3000/api/users/delete
Content-Type: application/json

{
  "_id": "62cc53068876811779d27cb0"
}



